theme: jekyll-theme-minimal
title: " "
description: " "
show_downloads: false
google_analytics: 
# Estas l√≠neas desactivan los enlaces de GitHub
github:
  is_project_page: false
  show_downloads: false
  is_user_page: false
